include machines/sim-1/aircraft/common/Makefile.sources
include machines/sim-1/aircraft/flight_computer_machine/Makefile.sources
include machines/sim-1/aircraft/hardware_machine/Makefile.sources
include machines/sim-1/aircraft/radio_machine/Makefile.sources
