#!/bin/sh

MEMCHECK='valgrind -v --tool=memcheck --num-callers=50 --leak-check=yes --leak-resolution=high --show-reachable=yes'
MASSIF='valgrind --tool=massif'
DRD='valgrind --tool=drd'
VALGRIND=
GDB=

TARGET="$DIST"
if [ "$TARGET" = "" ]; then
	TARGET="$(uname -m)"
fi
export GLIBCXX_FORCE_NEW=1
make -C src && $VALGRIND $GDB src/build/"$TARGET"/xefis "$@"

