#!/bin/sh

MEMCHECK='valgrind -v --tool=memcheck --num-callers=50 --leak-check=yes --leak-resolution=high --show-reachable=yes'
MASSIF='valgrind --tool=massif'
DRD='valgrind --tool=drd'
VALGRIND=
GDB=

# Copy of Makefile.local
THREADS=4
VERBOSE=0
DEBUG=1
PROFILING=0
RELEASE=0

if [ "$DEBUG" = "1" ] || [ "$VALGRIND" != "" ] || [ "$GDB" != "" ]; then
	export GLIBCXX_FORCE_NEW=1
fi

BUILDID_ARCH="$(uname -m)"

if [ "$PROFILING" = "1" ]; then
	BUILDID_PROFILING='-profiling'
fi

if [ "$DEBUG" = "1" ]; then
	BUILDID_DEBUG='-debug'
fi

if [ "$PROFILE" != "" ]; then
	BUILDID_PROFILE="-$PROFILE"
fi

export BUILDID="$BUILDID_ARCH$BUILDID_PROFILING$BUILDID_DEBUG$BUILDID_PROFILE"
echo $BUILDID
echo

execute()
{
	pushd src
	$VALGRIND $GDB build/"$BUILDID"/xefis "$@"
	popd
}

make -j4 -C src && execute "$@"

