# TODO make and use XEFIS_MACHINE_HEADERS and _SOURCES, then in main Makefile prepend machines/ (or machines/) to all sources.
XEFIS_HEADERS += machines/cthulhu_gcs/screens/pfd.h
XEFIS_HEADERS += machines/cthulhu_gcs/cthulhu_gcs.h
XEFIS_HEADERS += machines/cthulhu_gcs/warthog_stick.h
XEFIS_HEADERS += machines/cthulhu_gcs/layout_pfd.h
XEFIS_HEADERS += machines/cthulhu_gcs/loop.h
XEFIS_HEADERS += machines/cthulhu_gcs/utility.h
XEFIS_HEADERS += machines/cthulhu_gcs/warthog_stick.h
XEFIS_HEADERS += machines/cthulhu_shared/link_io.h
XEFIS_HEADERS += machines/cthulhu_shared/link_protocol.h

XEFIS_SOURCES += machines/cthulhu_gcs/screens/pfd.cc
XEFIS_SOURCES += machines/cthulhu_gcs/cthulhu_gcs.cc
XEFIS_SOURCES += machines/cthulhu_gcs/loop.cc

