include machines/sim-1/aircraft/common/Makefile.sources
include machines/sim-1/common/Makefile.sources

MACHINE_sim_1_AIRCRAFT_FLIGHT_COMPUTER_MACHINE_FILES += flight_computer_machine.cc
MACHINE_sim_1_AIRCRAFT_FLIGHT_COMPUTER_MACHINE_FILES += flight_computer_machine.h
MACHINE_sim_1_AIRCRAFT_FLIGHT_COMPUTER_MACHINE_FILES += flight_computer_modules.cc
MACHINE_sim_1_AIRCRAFT_FLIGHT_COMPUTER_MACHINE_FILES += flight_computer_modules.h

XEFIS_MACHINES.sim-1/aircraft/flight_computer_machine.sources += $(MACHINE_sim_1_AIRCRAFT_COMMON_FILES)
XEFIS_MACHINES.sim-1/aircraft/flight_computer_machine.sources += $(MACHINE_sim_1_COMMON_FILES)
XEFIS_MACHINES.sim-1/aircraft/flight_computer_machine.sources += $(MACHINE_sim_1_AIRCRAFT_FLIGHT_COMPUTER_MACHINE_FILES)
XEFIS_MACHINES.sim-1/aircraft/flight_computer_machine.sources += make_xefis_machine.cc
