include machines/sim-1/common/Makefile.sources

MACHINE_sim_1_GROUND_STATION_RADIO_MACHINE_FILES += radio_machine.cc
MACHINE_sim_1_GROUND_STATION_RADIO_MACHINE_FILES += radio_machine.h

XEFIS_MACHINES.sim-1/ground_station/radio_machine.sources += $(MACHINE_sim_1_COMMON_FILES)
XEFIS_MACHINES.sim-1/ground_station/radio_machine.sources += $(MACHINE_sim_1_GROUND_STATION_RADIO_MACHINE_FILES)
