XEFIS_MACHINE_HEADERS += test_instruments/test_instruments_machine.h
XEFIS_MACHINE_HEADERS += test_instruments/test_screen.h

XEFIS_MACHINE_SOURCES += test_instruments/test_instruments_machine.cc
XEFIS_MACHINE_SOURCES += test_instruments/test_screen.cc

