/* vim:ts=4
 *
 * Copyleft 2012…2016  Michał Gawron
 * Marduk Unix Labs, http://mulabs.org/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Visit http://www.gnu.org/licenses/gpl-3.0.html for more information on licensing.
 */

// Local:
#include "licenses.h"

// Standard:
#include <cstddef>


namespace xf::licenses {

const char* main =
	"This program is free software: you can redistribute it and/or modify\n"
	"it under the terms of the GNU General Public License as published by\n"
	"the Free Software Foundation, either version 3 of the License, or\n"
	"(at your option) any later version.\n"
	"Read LICENSE.software for more information.";

const char* font_crystal =
	"The Crystal font was crated by Jerry Fitzpatrick.\n"
	"Read LICENSE.fonts for more information.";

const char* lib_half =
	"The MIT License\n"
	"\n"
	"Copyright (c) 2012-2013 Christian Rau\n"
	"\n"
	"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
	"of this software and associated documentation files (the \"Software\"), to deal\n"
	"in the Software without restriction, including without limitation the rights\n"
	"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
	"copies of the Software, and to permit persons to whom the Software is\n"
	"furnished to do so, subject to the following conditions:\n"
	"\n"
	"The above copyright notice and this permission notice shall be included in\n"
	"all copies or substantial portions of the Software.\n"
	"\n"
	"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
	"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
	"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
	"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
	"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
	"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
	"THE SOFTWARE.";

const char* lib_kdtreeplusplus =
	"\"The Artistic Licence 2.0\"\n"
	"Copyright (c) 2000-2006, The Perl Foundation.\n"
	"http://www.perlfoundation.org/legal/licenses/artistic-2_0.html\n"
	"\n"
	"Everyone is permitted to copy and distribute verbatim copies of this license\n"
	"document, but changing it is not allowed.\n"
	"\n"
	"Preamble\n"
	"~~~~~~~~\n"
	"This license establishes the terms under which a given free software Package\n"
	"may be copied, modified, distributed, and/or redistributed. The intent is that\n"
	"the Copyright Holder maintains some artistic control over the development of\n"
	"that Package while still keeping the Package available as open source and free\n"
	"software.\n"
	"\n"
	"You are always permitted to make arrangements wholly outside of this license\n"
	"directly with the Copyright Holder of a given Package. If the terms of this\n"
	"license do not permit the full use that you propose to make of the Package,\n"
	"you should contact the Copyright Holder and seek a different licensing\n"
	"arrangement.\n"
	"\n"
	"Definitions\n"
	"~~~~~~~~~~~\n"
	"\"Copyright Holder\" means the individual(s) or organization(s) named in the\n"
	"copyright notice for the entire Package.\n"
	"\n"
	"\"Contributor\" means any party that has contributed code or other material to\n"
	"the Package, in accordance with the Copyright Holder's procedures.\n"
	"\n"
	"\"You\" and \"your\" means any person who would like to copy, distribute, or\n"
	"modify the Package.\n"
	"\n"
	"\"Package\" means the collection of files distributed by the Copyright Holder,\n"
	"and derivatives of that collection and/or of those files. A given Package may\n"
	"consist of either the Standard Version, or a Modified Version.\n"
	"\n"
	"\"Distribute\" means providing a copy of the Package or making it accessible to\n"
	"anyone else, or in the case of a company or organization, to others outside of\n"
	"your company or organization.\n"
	"\n"
	"\"Distributor Fee\" means any fee that you charge for Distributing this Package\n"
	"or providing support for this Package to another party. It does not mean\n"
	"licensing fees.\n"
	"\n"
	"\"Standard Version\" refers to the Package if it has not been modified, or has\n"
	"been modified only in ways explicitly requested by the Copyright Holder.\n"
	"\n"
	"\"Modified Version\" means the Package, if it has been changed, and such changes\n"
	"were not explicitly requested by the Copyright Holder.\n"
	"\n"
	"\"Original License\" means this Artistic License as Distributed with the\n"
	"Standard Version of the Package, in its current version or as it may be\n"
	"modified by The Perl Foundation in the future.\n"
	"\n"
	"\"Source\" form means the source code, documentation source, and configuration\n"
	"files for the Package.\n"
	"\n"
	"\"Compiled\" form means the compiled bytecode, object code, binary, or any other\n"
	"form resulting from mechanical transformation or translation of the Source\n"
	"form.\n"
	"\n"
	"Permission for Use and Modification Without Distribution\n"
	"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
	"(1) You are permitted to use the Standard Version and create and use Modified\n"
	"Versions for any purpose without restriction, provided that you do not\n"
	"Distribute the Modified Version.\n"
	"\n"
	"Permissions for Redistribution of the Standard Version\n"
	"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
	"(2) You may Distribute verbatim copies of the Source form of the Standard\n"
	"Version of this Package in any medium without restriction, either gratis or\n"
	"for a Distributor Fee, provided that you duplicate all of the original\n"
	"copyright notices and associated disclaimers. At your discretion, such\n"
	"verbatim copies may or may not include a Compiled form of the Package.\n"
	"\n"
	"(3) You may apply any bug fixes, portability changes, and other modifications\n"
	"made available from the Copyright Holder. The resulting Package will still be\n"
	"considered the Standard Version, and as such will be subject to the Original\n"
	"License.\n"
	"\n"
	"Distribution of Modified Versions of the Package as Source\n"
	"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
	"(4) You may Distribute your Modified Version as Source (either gratis or for\n"
	"a Distributor Fee, and with or without a Compiled form of the Modified\n"
	"Version) provided that you clearly document how it differs from the Standard\n"
	"Version, including, but not limited to, documenting any non-standard features,\n"
	"executables, or modules, and provided that you do at least ONE of the\n"
	"following:\n"
	"\n"
	"    (a) make the Modified Version available to the Copyright Holder of the\n"
	"        Standard Version, under the Original License, so that the Copyright\n"
	"        Holder may include your modifications in the Standard Version.\n"
	"    (b) ensure that installation of your Modified Version does not prevent the\n"
	"        user installing or running the Standard Version. In addition, the\n"
	"        Modified Version must bear a name that is different from the name of\n"
	"        the Standard Version.\n"
	"    (c) allow anyone who receives a copy of the Modified Version to make the\n"
	"        Source form of the Modified Version available to others under\n"
	"        (i) the Original License or\n"
	"        (ii) a license that permits the licensee to freely copy, modify and\n"
	"             redistribute the Modified Version using the same licensing terms\n"
	"             that apply to the copy that the licensee received, and requires\n"
	"             that the Source form of the Modified Version, and of any works\n"
	"             derived from it, be made freely available in that license fees\n"
	"             are prohibited but Distributor Fees are allowed.\n"
	"\n"
	"Distribution of Compiled Forms of the Standard Version or Modified Versions\n"
	"without the Source\n"
	"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
	"(5) You may Distribute Compiled forms of the Standard Version without the\n"
	"Source, provided that you include complete instructions on how to get the\n"
	"Source of the Standard Version. Such instructions must be valid at the time of\n"
	"your distribution. If these instructions, at any time while you are carrying\n"
	"out such distribution, become invalid, you must provide new instructions on\n"
	"demand or cease further distribution. If you provide valid instructions or\n"
	"cease distribution within thirty days after you become aware that the\n"
	"instructions are invalid, then you do not forfeit any of your rights under\n"
	"this license.\n"
	"\n"
	"(6) You may Distribute a Modified Version in Compiled form without the Source,\n"
	"provided that you comply with Section 4 with respect to the Source of the\n"
	"Modified Version.\n"
	"\n"
	"Aggregating or Linking the Package\n"
	"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
	"(7) You may aggregate the Package (either the Standard Version or Modified\n"
	"Version) with other packages and Distribute the resulting aggregation provided\n"
	"that you do not charge a licensing fee for the Package. Distributor Fees are\n"
	"permitted, and licensing fees for other components in the aggregation are\n"
	"permitted. The terms of this license apply to the use and Distribution of the\n"
	"Standard or Modified Versions as included in the aggregation.\n"
	"\n"
	"(8) You are permitted to link Modified and Standard Versions with other works,\n"
	"to embed the Package in a larger work of your own, or to build stand-alone\n"
	"binary or bytecode versions of applications that include the Package, and\n"
	"Distribute the result without restriction, provided the result does not expose\n"
	"a direct interface to the Package.\n"
	"\n"
	"Items That are Not Considered Part of a Modified Version\n"
	"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
	"(9) Works (including, but not limited to, modules and scripts) that merely\n"
	"extend or make use of the Package, do not, by themselves, cause the Package to\n"
	"be a Modified Version. In addition, such works are not considered parts of the\n"
	"Package itself, and are not subject to the terms of this license.\n"
	"\n"
	"General Provisions\n"
	"~~~~~~~~~~~~~~~~~~\n"
	"(10) Any use, modification, and distribution of the Standard or Modified\n"
	"Versions is governed by this Artistic License. By using, modifying or\n"
	"distributing the Package, you accept this license. Do not use, modify, or\n"
	"distribute the Package, if you do not accept this license.\n"
	"\n"
	"(11) If your Modified Version has been derived from a Modified Version made by\n"
	"someone other than you, you are nevertheless required to ensure that your\n"
	"Modified Version complies with the requirements of this license.\n"
	"\n"
	"(12) This license does not grant you the right to use any trademark, service\n"
	"mark, tradename, or logo of the Copyright Holder.\n"
	"\n"
	"(13) This license includes the non-exclusive, worldwide, free-of-charge patent\n"
	"license to make, have made, use, offer to sell, sell, import and otherwise\n"
	"transfer the Package with respect to any patent claims licensable by the\n"
	"Copyright Holder that are necessarily infringed by the Package. If you\n"
	"institute patent litigation (including a cross-claim or counterclaim) against\n"
	"any party alleging that the Package constitutes direct or contributory patent\n"
	"infringement, then this Artistic License to you shall terminate on the date\n"
	"that such litigation is filed.\n"
	"\n"
	"(14) Disclaimer of Warranty: THE PACKAGE IS PROVIDED BY THE COPYRIGHT HOLDER\n"
	"AND CONTRIBUTORS \"AS IS' AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES. THE\n"
	"IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR\n"
	"NON-INFRINGEMENT ARE DISCLAIMED TO THE EXTENT PERMITTED BY YOUR LOCAL LAW.\n"
	"UNLESS REQUIRED BY LAW, NO COPYRIGHT HOLDER OR CONTRIBUTOR WILL BE LIABLE FOR\n"
	"ANY DIRECT, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING IN ANY WAY\n"
	"OUT OF THE USE OF THE PACKAGE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH\n"
	"DAMAGE.";

const char* lib_type_safe =
	"MIT License\n"
	"\n"
	"Copyright (c) 2016-2019 Jonathan Müller\n"
	"\n"
	"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
	"of this software and associated documentation files (the \"Software\"), to deal\n"
	"in the Software without restriction, including without limitation the rights\n"
	"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
	"copies of the Software, and to permit persons to whom the Software is\n"
	"furnished to do so, subject to the following conditions:\n"
	"\n"
	"The above copyright notice and this permission notice shall be included in all\n"
	"copies or substantial portions of the Software.\n"
	"\n"
	"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
	"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
	"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
	"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
	"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
	"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
	"SOFTWARE.";

const char* lib_microsoft_gsl =
	"Copyright (c) 2015 Microsoft Corporation. All rights reserved.\n"
	"\n"
	"This code is licensed under the MIT License (MIT).\n"
	"\n"
	"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
	"of this software and associated documentation files (the \"Software\"), to deal\n"
	"in the Software without restriction, including without limitation the rights\n"
	"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies\n"
	"of the Software, and to permit persons to whom the Software is furnished to do\n"
	"so, subject to the following conditions:\n"
	"\n"
	"The above copyright notice and this permission notice shall be included in all\n"
	"copies or substantial portions of the Software.\n"
	"\n"
	"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
	"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
	"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
	"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
	"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
	"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
	"THE SOFTWARE.\n";

} // namespace xf::licenses

