include machines/sim-1/aircraft/common/Makefile.sources
include machines/sim-1/common/Makefile.sources

MACHINE_sim_1_AIRCRAFT_HARDWARE_MACHINE_FILES += hardware_machine.cc
MACHINE_sim_1_AIRCRAFT_HARDWARE_MACHINE_FILES += hardware_machine.h
MACHINE_sim_1_AIRCRAFT_HARDWARE_MACHINE_FILES += hardware_modules.cc
MACHINE_sim_1_AIRCRAFT_HARDWARE_MACHINE_FILES += hardware_modules.h
MACHINE_sim_1_AIRCRAFT_HARDWARE_MACHINE_FILES += real_hardware_modules.h

XEFIS_MACHINES.sim-1/aircraft/hardware_machine.sources += $(MACHINE_sim_1_AIRCRAFT_COMMON_FILES)
XEFIS_MACHINES.sim-1/aircraft/hardware_machine.sources += $(MACHINE_sim_1_COMMON_FILES)
XEFIS_MACHINES.sim-1/aircraft/hardware_machine.sources += $(MACHINE_sim_1_AIRCRAFT_HARDWARE_MACHINE_FILES)
