#!/bin/sh

if git diff --quiet --exit-code --stat && git diff --stat --cached --quiet --exit-code; then
	total="$(git ls-files | wc -l)"
	n=0
	git ls-files -z | while IFS= read -r -d '' path; do
		n=$((n+1))
		echo -ne "$n/$total\r"
		if [ -f "$path" ] && ! [ -L "$path" ]; then
			year="$(git log --follow --format=%ad --date=format:%Y -- "$path" | tail -n 1)"
			if [ "$year" != "" ]; then
				sed -E -i 's/Copyleft ([0-9]{4})  /Copyleft '"$year"'  /g' -- "$path"
				#printf 'file: %s %s\n' "$path" "$year"
			else
				echo "Warning: no year found for path -- $path"
			fi
		else
			echo "Skipping non-regular file -- $path"
		fi
	done
	printf '\r\033[KAll done ('"$total"' files)\n'
else
	echo "Uncommited changes found. Stash or commit them beforehand."
fi
