LANGUAGE=en # This is for Vim, when doing :make Vim jumps to right file on errors, but only when Make uses english messages.
.PHONY: all

all:
	+$(MAKE) all -C ..

%:
	@CWD="`pwd`" cd .. && $(MAKE) -s $@ && cd $$CWD

